<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Hello bookdown | Statistical Rethinking Workbook</title>
  <meta name="description" content="This is a workbook for notes and problems as I work through Statistical Rethinking by Richard McElreath" />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Hello bookdown | Statistical Rethinking Workbook" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This is a workbook for notes and problems as I work through Statistical Rethinking by Richard McElreath" />
  <meta name="github-repo" content="agberg/statistical_rethinking_workbook" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Hello bookdown | Statistical Rethinking Workbook" />
  
  <meta name="twitter:description" content="This is a workbook for notes and problems as I work through Statistical Rethinking by Richard McElreath" />
  

<meta name="author" content="Aaron Berg" />


<meta name="date" content="2022-02-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>
<link rel="next" href="cross.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Statistical Rethinking Workbook</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#usage"><i class="fa fa-check"></i><b>1.1</b> Usage</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#render-book"><i class="fa fa-check"></i><b>1.2</b> Render book</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#preview-book"><i class="fa fa-check"></i><b>1.3</b> Preview book</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="hello-bookdown.html"><a href="hello-bookdown.html"><i class="fa fa-check"></i><b>2</b> Hello bookdown</a>
<ul>
<li class="chapter" data-level="2.1" data-path="hello-bookdown.html"><a href="hello-bookdown.html#a-section"><i class="fa fa-check"></i><b>2.1</b> A section</a>
<ul>
<li class="chapter" data-level="" data-path="hello-bookdown.html"><a href="hello-bookdown.html#an-unnumbered-section"><i class="fa fa-check"></i>An unnumbered section</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="hello-bookdown.html"><a href="hello-bookdown.html#lectures"><i class="fa fa-check"></i><b>2.2</b> Lectures</a></li>
<li class="chapter" data-level="2.3" data-path="hello-bookdown.html"><a href="hello-bookdown.html#exercises"><i class="fa fa-check"></i><b>2.3</b> Exercises</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="hello-bookdown.html"><a href="hello-bookdown.html#chapter-1"><i class="fa fa-check"></i><b>2.3.1</b> Chapter 1</a></li>
<li class="chapter" data-level="2.3.2" data-path="hello-bookdown.html"><a href="hello-bookdown.html#chapter-2"><i class="fa fa-check"></i><b>2.3.2</b> Chapter 2</a></li>
<li class="chapter" data-level="2.3.3" data-path="hello-bookdown.html"><a href="hello-bookdown.html#chapter-3"><i class="fa fa-check"></i><b>2.3.3</b> Chapter 3</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="hello-bookdown.html"><a href="hello-bookdown.html#homework"><i class="fa fa-check"></i><b>2.4</b> Homework</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="cross.html"><a href="cross.html"><i class="fa fa-check"></i><b>3</b> Cross-references</a>
<ul>
<li class="chapter" data-level="3.1" data-path="cross.html"><a href="cross.html#chapters-and-sub-chapters"><i class="fa fa-check"></i><b>3.1</b> Chapters and sub-chapters</a></li>
<li class="chapter" data-level="3.2" data-path="cross.html"><a href="cross.html#captioned-figures-and-tables"><i class="fa fa-check"></i><b>3.2</b> Captioned figures and tables</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="parts.html"><a href="parts.html"><i class="fa fa-check"></i><b>4</b> Parts</a></li>
<li class="chapter" data-level="5" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html"><i class="fa fa-check"></i><b>5</b> Footnotes and citations</a>
<ul>
<li class="chapter" data-level="5.1" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#footnotes"><i class="fa fa-check"></i><b>5.1</b> Footnotes</a></li>
<li class="chapter" data-level="5.2" data-path="footnotes-and-citations.html"><a href="footnotes-and-citations.html#citations"><i class="fa fa-check"></i><b>5.2</b> Citations</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="blocks.html"><a href="blocks.html"><i class="fa fa-check"></i><b>6</b> Blocks</a>
<ul>
<li class="chapter" data-level="6.1" data-path="blocks.html"><a href="blocks.html#equations"><i class="fa fa-check"></i><b>6.1</b> Equations</a></li>
<li class="chapter" data-level="6.2" data-path="blocks.html"><a href="blocks.html#theorems-and-proofs"><i class="fa fa-check"></i><b>6.2</b> Theorems and proofs</a></li>
<li class="chapter" data-level="6.3" data-path="blocks.html"><a href="blocks.html#callout-blocks"><i class="fa fa-check"></i><b>6.3</b> Callout blocks</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="sharing-your-book.html"><a href="sharing-your-book.html"><i class="fa fa-check"></i><b>7</b> Sharing your book</a>
<ul>
<li class="chapter" data-level="7.1" data-path="sharing-your-book.html"><a href="sharing-your-book.html#publishing"><i class="fa fa-check"></i><b>7.1</b> Publishing</a></li>
<li class="chapter" data-level="7.2" data-path="sharing-your-book.html"><a href="sharing-your-book.html#pages"><i class="fa fa-check"></i><b>7.2</b> 404 pages</a></li>
<li class="chapter" data-level="7.3" data-path="sharing-your-book.html"><a href="sharing-your-book.html#metadata-for-sharing"><i class="fa fa-check"></i><b>7.3</b> Metadata for sharing</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Rethinking Workbook</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="hello-bookdown" class="section level1" number="2">
<h1><span class="header-section-number">Chapter 2</span> Hello bookdown</h1>
<p>All chapters start with a first-level heading followed by your chapter title, like the line above. There should be only one first-level heading (<code>#</code>) per .Rmd file.</p>
<div id="a-section" class="section level2" number="2.1">
<h2><span class="header-section-number">2.1</span> A section</h2>
<p>All chapter sections start with a second-level (<code>##</code>) or higher heading followed by your section title, like the sections above and below here. You can have as many as you want within a chapter.</p>
<div id="an-unnumbered-section" class="section level3 unnumbered">
<h3>An unnumbered section</h3>
<p>Chapters and sections are numbered by default. To un-number a heading, add a <code>{.unnumbered}</code> or the shorter <code>{-}</code> at the end of the heading, like in this section.</p>
<p>The first week covers <a href="https://bookdown.org/content/4857/the-golem-of-prague.html">Chapter 1 (The Golem of Prague)</a>, <a href="https://bookdown.org/content/4857/small-worlds-and-large-worlds.html">Chapter 2 (Small Worlds and Large Worlds)</a>, and <a href="https://bookdown.org/content/4857/sampling-the-imaginary.html">Chapter 3 (Sampling the Imaginary)</a>.</p>
</div>
</div>
<div id="lectures" class="section level2" number="2.2">
<h2><span class="header-section-number">2.2</span> Lectures</h2>
<p>Lecture 1:</p>
<iframe src="https://www.youtube.com/embed/cclUd_HoRlo" width="100%" height="400px" data-external="1">
</iframe>
<p>Lecture 2:</p>
<iframe src="https://www.youtube.com/embed/guTdrfycW2Q" width="100%" height="400px" data-external="1">
</iframe>
</div>
<div id="exercises" class="section level2" number="2.3">
<h2><span class="header-section-number">2.3</span> Exercises</h2>
<div id="chapter-1" class="section level3" number="2.3.1">
<h3><span class="header-section-number">2.3.1</span> Chapter 1</h3>
<p>There are no exercises for Chapter 1.</p>
</div>
<div id="chapter-2" class="section level3" number="2.3.2">
<h3><span class="header-section-number">2.3.2</span> Chapter 2</h3>
<div class="question">
<blockquote>
<p><strong>2E1.</strong> Which of the expressions below correspond to the statement: <em>the probability of rain on Monday</em>?<br />
(1) Pr(rain)<br />
(2) Pr(rain|Monday)<br />
(3) Pr(Monday|rain)<br />
(4) Pr(rain, Monday) / Pr(Monday)</p>
</blockquote>
</div>
<p>I take this question to mean the probability of rain given that it is Monday. That means both (2) and (4) are correct.</p>
<div class="question">
<blockquote>
<p><strong>2E2.</strong> Which of the following statements corresponds to the expression: Pr(Monday|rain)?<br />
(1) The probability of rain on Monday.<br />
(2) The probability of rain, given that it is Monday.<br />
(3) The probability that it is Monday, given that it is raining.<br />
(4) The probability that it is Monday and that it is raining.</p>
</blockquote>
</div>
<p>Only answer (3) corresponds to the expression Pr(Monday|rain).</p>
<div class="question">
<blockquote>
<p><strong>2E3.</strong> Which of the following expressions below correspond to the statement: <em>the probability that it is Monday, given that it is raining</em>?<br />
(1) Pr(Monday|rain)<br />
(2) Pr(rain|Monday)<br />
(3) Pr(rain|Monday) Pr(Monday)<br />
(4) Pr(rain|Monday) Pr(Monday) / Pr(rain)<br />
(5) Pr(Monday|rain) Pr(rain) / Pr(Monday)</p>
</blockquote>
</div>
<p>There are again two correct answers. Answer option (1) is the standard notation for the conditional probability. Answer option (4) is equivalent, as this is <a href="https://en.wikipedia.org/wiki/Bayes&#39;_theorem#Statement_of_theorem">Bayes’ Theorem</a>.</p>
<div class="question">
<blockquote>
<p><strong>2E4.</strong> The Bayesian statistician Bruno de Finetti (1906–1985) began his 1973 book on probability theory with the dedication: “PROBABILITY DOES NOT EXIST.” The capitals appeared in the original, so I imagine de Finetti wanted us to shout this statement. What he meant is that probability is a device for describing uncertainty from the perspective of an observer with limited knowledge; it has no objective reality. Discuss the globe tossing example from the chapter, in light of this statement. What does it mean to say “the probability of water is 0.7?”</p>
</blockquote>
</div>
<p>The idea is that probability is only a subjective perception of the likelihood that something will happen. In the globe tossing example, the result will always be either “land” or “water” (i.e., 0 or 1). When we toss the globe, we don’t know what the result will be, but we know it will always be “land” or “water.” To express our uncertainty in the outcome, we use probability. Because we know that water is more likely than land, we may say that the probability of “water” is 0.7; however, we’ll never actually observe a result of 0.7 waters, or observe any probability. We will only ever observe the two results of “land” and “water.”</p>
<div class="question">
<blockquote>
<p><strong>2M1.</strong> Recall the globe tossing model from the chapter. Compute and plot the grid approximate posterior distribution for each of the following sets of observations. In each case, assume a uniform prior for <em>p</em>.
(1) W, W, W
(2) W, W, W, L
(3) L, W, W, L, W, W, W</p>
</blockquote>
</div>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="hello-bookdown.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-2"><a href="hello-bookdown.html#cb3-2" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">p_grid =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">20</span>),</span>
<span id="cb3-3"><a href="hello-bookdown.html#cb3-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">prior =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="at">times =</span> <span class="dv">20</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="hello-bookdown.html#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">likelihood_1 =</span> <span class="fu">dbinom</span>(<span class="dv">3</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb3-5"><a href="hello-bookdown.html#cb3-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood_2 =</span> <span class="fu">dbinom</span>(<span class="dv">3</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb3-6"><a href="hello-bookdown.html#cb3-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood_3 =</span> <span class="fu">dbinom</span>(<span class="dv">5</span>, <span class="at">size =</span> <span class="dv">7</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb3-7"><a href="hello-bookdown.html#cb3-7" aria-hidden="true" tabindex="-1"></a>         <span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;likelihood&quot;</span>), <span class="sc">~</span> .x <span class="sc">*</span> prior),</span>
<span id="cb3-8"><a href="hello-bookdown.html#cb3-8" aria-hidden="true" tabindex="-1"></a>         <span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;likelihood&quot;</span>), <span class="sc">~</span> .x <span class="sc">/</span> <span class="fu">sum</span>(.x))) <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="hello-bookdown.html#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;likelihood&quot;</span>), <span class="at">names_to =</span> <span class="st">&quot;pattern&quot;</span>,</span>
<span id="cb3-10"><a href="hello-bookdown.html#cb3-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;posterior&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-11"><a href="hello-bookdown.html#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(pattern, <span class="fu">c</span>(<span class="cn">NA</span>, <span class="st">&quot;pattern&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;_&quot;</span>, <span class="at">convert =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="hello-bookdown.html#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">obs =</span> <span class="fu">case_when</span>(pattern <span class="sc">==</span> 1L <span class="sc">~</span> <span class="st">&quot;W, W, W&quot;</span>,</span>
<span id="cb3-13"><a href="hello-bookdown.html#cb3-13" aria-hidden="true" tabindex="-1"></a>                         pattern <span class="sc">==</span> 2L <span class="sc">~</span> <span class="st">&quot;W, W, W, L&quot;</span>,</span>
<span id="cb3-14"><a href="hello-bookdown.html#cb3-14" aria-hidden="true" tabindex="-1"></a>                         pattern <span class="sc">==</span> 3L <span class="sc">~</span> <span class="st">&quot;L, W, W, L, W, W, W&quot;</span>))</span>
<span id="cb3-15"><a href="hello-bookdown.html#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dist, <span class="fu">aes</span>(<span class="at">x =</span> p_grid, <span class="at">y =</span> posterior)) <span class="sc">+</span></span>
<span id="cb3-16"><a href="hello-bookdown.html#cb3-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(<span class="fu">fct_inorder</span>(obs)), <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb3-17"><a href="hello-bookdown.html#cb3-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb3-18"><a href="hello-bookdown.html#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb3-19"><a href="hello-bookdown.html#cb3-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/e2m1-1.png" width="672" /></p>
<div class="question">
<blockquote>
<p><strong>2M2.</strong> Now assume a prior for <em>p</em> that is equal to zero when <em>p</em> &lt; 0.5 and is a positive constant when <em>p</em> ≥ 0.5. Again compute and plot the grid approximate posterior distribution for each of the sets of observations in the problem just above.</p>
</blockquote>
</div>
<p>For this problem we can use the same code as above, just altering how the prior is defined.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="hello-bookdown.html#cb4-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">p_grid =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">20</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="hello-bookdown.html#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prior =</span> <span class="fu">case_when</span>(p_grid <span class="sc">&lt;</span> <span class="fl">0.5</span> <span class="sc">~</span> 0L,</span>
<span id="cb4-3"><a href="hello-bookdown.html#cb4-3" aria-hidden="true" tabindex="-1"></a>                           <span class="cn">TRUE</span> <span class="sc">~</span> 1L),</span>
<span id="cb4-4"><a href="hello-bookdown.html#cb4-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood_1 =</span> <span class="fu">dbinom</span>(<span class="dv">3</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb4-5"><a href="hello-bookdown.html#cb4-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood_2 =</span> <span class="fu">dbinom</span>(<span class="dv">3</span>, <span class="at">size =</span> <span class="dv">4</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb4-6"><a href="hello-bookdown.html#cb4-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">likelihood_3 =</span> <span class="fu">dbinom</span>(<span class="dv">5</span>, <span class="at">size =</span> <span class="dv">7</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb4-7"><a href="hello-bookdown.html#cb4-7" aria-hidden="true" tabindex="-1"></a>         <span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;likelihood&quot;</span>), <span class="sc">~</span> .x <span class="sc">*</span> prior),</span>
<span id="cb4-8"><a href="hello-bookdown.html#cb4-8" aria-hidden="true" tabindex="-1"></a>         <span class="fu">across</span>(<span class="fu">starts_with</span>(<span class="st">&quot;likelihood&quot;</span>), <span class="sc">~</span> .x <span class="sc">/</span> <span class="fu">sum</span>(.x))) <span class="sc">%&gt;%</span></span>
<span id="cb4-9"><a href="hello-bookdown.html#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="fu">starts_with</span>(<span class="st">&quot;likelihood&quot;</span>), <span class="at">names_to =</span> <span class="st">&quot;pattern&quot;</span>,</span>
<span id="cb4-10"><a href="hello-bookdown.html#cb4-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">values_to =</span> <span class="st">&quot;posterior&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-11"><a href="hello-bookdown.html#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(pattern, <span class="fu">c</span>(<span class="cn">NA</span>, <span class="st">&quot;pattern&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;_&quot;</span>, <span class="at">convert =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-12"><a href="hello-bookdown.html#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">obs =</span> <span class="fu">case_when</span>(pattern <span class="sc">==</span> 1L <span class="sc">~</span> <span class="st">&quot;W, W, W&quot;</span>,</span>
<span id="cb4-13"><a href="hello-bookdown.html#cb4-13" aria-hidden="true" tabindex="-1"></a>                         pattern <span class="sc">==</span> 2L <span class="sc">~</span> <span class="st">&quot;W, W, W, L&quot;</span>,</span>
<span id="cb4-14"><a href="hello-bookdown.html#cb4-14" aria-hidden="true" tabindex="-1"></a>                         pattern <span class="sc">==</span> 3L <span class="sc">~</span> <span class="st">&quot;L, W, W, L, W, W, W&quot;</span>))</span>
<span id="cb4-15"><a href="hello-bookdown.html#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dist, <span class="fu">aes</span>(<span class="at">x =</span> p_grid, <span class="at">y =</span> posterior)) <span class="sc">+</span></span>
<span id="cb4-16"><a href="hello-bookdown.html#cb4-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="fu">vars</span>(<span class="fu">fct_inorder</span>(obs)), <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb4-17"><a href="hello-bookdown.html#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb4-18"><a href="hello-bookdown.html#cb4-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb4-19"><a href="hello-bookdown.html#cb4-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/e2m2-1.png" width="672" /></p>
<div class="question">
<blockquote>
<p><strong>2M3.</strong> Suppose there are two globes, one for Earth and one for Mars. The Earth globe is 70% covered in water. The Mars globe is 100% land. Further suppose that one of these globes—you don’t know which—was tossed in the air and produced a “land” observatiion. Assume that each globe was equally likely to be tossed. Show that the posterior probability that the globe was the Earth, conditional on seeing “land” (Pr(Earth|land)), is 0.23.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="hello-bookdown.html#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of land, given Earth</span></span>
<span id="cb5-2"><a href="hello-bookdown.html#cb5-2" aria-hidden="true" tabindex="-1"></a>p_le <span class="ot">&lt;-</span> <span class="fl">0.3</span></span>
<span id="cb5-3"><a href="hello-bookdown.html#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of land, given Mars</span></span>
<span id="cb5-4"><a href="hello-bookdown.html#cb5-4" aria-hidden="true" tabindex="-1"></a>p_lm <span class="ot">&lt;-</span> <span class="fl">1.0</span></span>
<span id="cb5-5"><a href="hello-bookdown.html#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of Earth</span></span>
<span id="cb5-6"><a href="hello-bookdown.html#cb5-6" aria-hidden="true" tabindex="-1"></a>p_e <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb5-7"><a href="hello-bookdown.html#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of land</span></span>
<span id="cb5-8"><a href="hello-bookdown.html#cb5-8" aria-hidden="true" tabindex="-1"></a>p_l <span class="ot">&lt;-</span> (p_e <span class="sc">*</span> p_le) <span class="sc">+</span> ((<span class="dv">1</span> <span class="sc">-</span> p_e) <span class="sc">*</span> p_lm)</span>
<span id="cb5-9"><a href="hello-bookdown.html#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of Earth, given land (using Bayes&#39; Theorem)</span></span>
<span id="cb5-10"><a href="hello-bookdown.html#cb5-10" aria-hidden="true" tabindex="-1"></a>p_el <span class="ot">&lt;-</span> (p_le <span class="sc">*</span> p_e) <span class="sc">/</span> p_l</span>
<span id="cb5-11"><a href="hello-bookdown.html#cb5-11" aria-hidden="true" tabindex="-1"></a>p_el</span></code></pre></div>
<pre><code>## [1] 0.2307692</code></pre>
<div class="question">
<blockquote>
<p><strong>2M4.</strong> Suppose you have a deck with only three cards. Each card has only two sides, and each side is either black or white. One card has two black sides. The second card has one black and one white side. The third card has two white sides. Now suppose all three cards are placed in a bag and shuffled. Someone reaches into the bag and pulls out a card and places it flat on a table. A black side is shown facing up, but you don’t know the color of the side facing down. Show that the probability that the other side is also black is 2/3. Use the counting method (Section 2 of the chapter) to approach this problem. This means counting up the ways that each card could produce the observed data (a black side faceing up on the table).</p>
</blockquote>
</div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="hello-bookdown.html#cb7-1" aria-hidden="true" tabindex="-1"></a>card_bb_likelihood <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb7-2"><a href="hello-bookdown.html#cb7-2" aria-hidden="true" tabindex="-1"></a>card_bw_likelihood <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb7-3"><a href="hello-bookdown.html#cb7-3" aria-hidden="true" tabindex="-1"></a>card_ww_likelihood <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb7-4"><a href="hello-bookdown.html#cb7-4" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">c</span>(card_bb_likelihood, card_bw_likelihood, card_ww_likelihood)</span>
<span id="cb7-5"><a href="hello-bookdown.html#cb7-5" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb7-6"><a href="hello-bookdown.html#cb7-6" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb7-7"><a href="hello-bookdown.html#cb7-7" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb7-8"><a href="hello-bookdown.html#cb7-8" aria-hidden="true" tabindex="-1"></a>posterior[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.6666667</code></pre>
<div class="question">
<blockquote>
<p><strong>2M5.</strong> Now suppose there are four cards: B/B, B/W, W/W, and another B/B. Again suppose a card is drawn from the bag and a black side appears face up. Again calculate the probability that the other side is black.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="hello-bookdown.html#cb9-1" aria-hidden="true" tabindex="-1"></a>card_bb_likelihood <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb9-2"><a href="hello-bookdown.html#cb9-2" aria-hidden="true" tabindex="-1"></a>card_bw_likelihood <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb9-3"><a href="hello-bookdown.html#cb9-3" aria-hidden="true" tabindex="-1"></a>card_ww_likelihood <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb9-4"><a href="hello-bookdown.html#cb9-4" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">c</span>(card_bb_likelihood, card_bw_likelihood, card_ww_likelihood,</span>
<span id="cb9-5"><a href="hello-bookdown.html#cb9-5" aria-hidden="true" tabindex="-1"></a>                card_bb_likelihood)</span>
<span id="cb9-6"><a href="hello-bookdown.html#cb9-6" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb9-7"><a href="hello-bookdown.html#cb9-7" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb9-8"><a href="hello-bookdown.html#cb9-8" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb9-9"><a href="hello-bookdown.html#cb9-9" aria-hidden="true" tabindex="-1"></a>posterior[<span class="dv">1</span>] <span class="sc">+</span> posterior[<span class="dv">4</span>]</span></code></pre></div>
<pre><code>## [1] 0.8</code></pre>
<div class="question">
<blockquote>
<p><strong>2M6.</strong> Imagine that black ink is heavy, and so cards with black sides are heavier than cards with white sides. As a result, it’s less likely that a card with black sides is pulled from the bag. So again assume there are three cards: B/B, B/W, and W/W. After experimenting a number of times, you conclude that for every way to pull the B/B card from the bag, there are 2 ways to pull the B/W card and 3 ways to pull the W/W card. Again suppose that a card is pulled and a black side appears face up. Show that the probability the other side is black is now 0.5. Use the counting method, as before.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="hello-bookdown.html#cb11-1" aria-hidden="true" tabindex="-1"></a>card_bb_likelihood <span class="ot">&lt;-</span> <span class="dv">2</span></span>
<span id="cb11-2"><a href="hello-bookdown.html#cb11-2" aria-hidden="true" tabindex="-1"></a>card_bw_likelihood <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb11-3"><a href="hello-bookdown.html#cb11-3" aria-hidden="true" tabindex="-1"></a>card_ww_likelihood <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb11-4"><a href="hello-bookdown.html#cb11-4" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">c</span>(card_bb_likelihood, card_bw_likelihood, card_ww_likelihood)</span>
<span id="cb11-5"><a href="hello-bookdown.html#cb11-5" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb11-6"><a href="hello-bookdown.html#cb11-6" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb11-7"><a href="hello-bookdown.html#cb11-7" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb11-8"><a href="hello-bookdown.html#cb11-8" aria-hidden="true" tabindex="-1"></a>posterior[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.5</code></pre>
<div class="question">
<blockquote>
<p><strong>2M7.</strong> Assume again the original card problem, with a single card showing a black side face up. Before looking at the other side, we draw another card from the bag and lay it face up on the table. The face that is shown on the new card is white. Show that the probability that the first card, the one showing a black side, has black on its other side is now 0.75. Use the counting method, if you can. Hint: Treat this like the sequence of globe tosses, countng all the ways to see each observation, for each possiible first card.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="hello-bookdown.html#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2 choices for first card, with 3 options for second card: 2 W/W + 1 W/B</span></span>
<span id="cb13-2"><a href="hello-bookdown.html#cb13-2" aria-hidden="true" tabindex="-1"></a>card_bb_likelihood <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="dv">3</span> </span>
<span id="cb13-3"><a href="hello-bookdown.html#cb13-3" aria-hidden="true" tabindex="-1"></a>card_wb_likelihood <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">*</span> <span class="dv">2</span> </span>
<span id="cb13-4"><a href="hello-bookdown.html#cb13-4" aria-hidden="true" tabindex="-1"></a>card_ww_likelihood <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb13-5"><a href="hello-bookdown.html#cb13-5" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">c</span>(card_bb_likelihood, card_wb_likelihood, card_ww_likelihood)</span>
<span id="cb13-6"><a href="hello-bookdown.html#cb13-6" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb13-7"><a href="hello-bookdown.html#cb13-7" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> prior <span class="sc">*</span> likelihood</span>
<span id="cb13-8"><a href="hello-bookdown.html#cb13-8" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb13-9"><a href="hello-bookdown.html#cb13-9" aria-hidden="true" tabindex="-1"></a>posterior[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.75</code></pre>
<div class="question">
<blockquote>
<p><strong>2H1.</strong> Suppose there are two species of panda bear. Both are equally common in the wild and live in the sample places. They look exactly alike and eat the same food, and there is yet no genetic assay capable of telling them apart. They differ however in their family sizes. Species A gives birth to twins 10% of the time, otherwise birthing a single infant. Species births twins 20% of the time, ottherwise birthing singleton infants. Assume these numbers are known with certainty, from many years of field research.<br />
Now suppose you are managing a captive panda breeding program. You have a newe female panda of unknown species, and she has just given birth to twins. What is the probability that her next birth will also be twins?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="hello-bookdown.html#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># After first birth, likelihood of species A and B is equal to the rate the</span></span>
<span id="cb15-2"><a href="hello-bookdown.html#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># species give birth to twins</span></span>
<span id="cb15-3"><a href="hello-bookdown.html#cb15-3" aria-hidden="true" tabindex="-1"></a>a_likelihood <span class="ot">&lt;-</span> <span class="fl">0.1</span></span>
<span id="cb15-4"><a href="hello-bookdown.html#cb15-4" aria-hidden="true" tabindex="-1"></a>b_likelihood <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb15-5"><a href="hello-bookdown.html#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Next calculate the posterior probability that the panda belongs to each</span></span>
<span id="cb15-6"><a href="hello-bookdown.html#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># species, assume species are equally likely</span></span>
<span id="cb15-7"><a href="hello-bookdown.html#cb15-7" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">c</span>(a_likelihood, b_likelihood)</span>
<span id="cb15-8"><a href="hello-bookdown.html#cb15-8" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>) </span>
<span id="cb15-9"><a href="hello-bookdown.html#cb15-9" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb15-10"><a href="hello-bookdown.html#cb15-10" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb15-11"><a href="hello-bookdown.html#cb15-11" aria-hidden="true" tabindex="-1"></a>posterior</span></code></pre></div>
<pre><code>## [1] 0.3333333 0.6666667</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="hello-bookdown.html#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The probability the next birth is twins is the probability the panda belongs</span></span>
<span id="cb17-2"><a href="hello-bookdown.html#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># to each species times the likelihood each species gives birth to twins</span></span>
<span id="cb17-3"><a href="hello-bookdown.html#cb17-3" aria-hidden="true" tabindex="-1"></a>(posterior[<span class="dv">1</span>] <span class="sc">*</span> a_likelihood) <span class="sc">+</span> (posterior[<span class="dv">2</span>] <span class="sc">*</span> b_likelihood)</span></code></pre></div>
<pre><code>## [1] 0.1666667</code></pre>
<div class="question">
<blockquote>
<p><strong>2H2.</strong> Recall all the facts from the problem above. Now compute the probability that the panda we have is from species A, asssuming we have observed only the first birth at that it was twins.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="hello-bookdown.html#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of species A</span></span>
<span id="cb19-2"><a href="hello-bookdown.html#cb19-2" aria-hidden="true" tabindex="-1"></a>p_a <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb19-3"><a href="hello-bookdown.html#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of twins, given species A</span></span>
<span id="cb19-4"><a href="hello-bookdown.html#cb19-4" aria-hidden="true" tabindex="-1"></a>p_ta <span class="ot">&lt;-</span> <span class="fl">0.1</span></span>
<span id="cb19-5"><a href="hello-bookdown.html#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of twins, given species B</span></span>
<span id="cb19-6"><a href="hello-bookdown.html#cb19-6" aria-hidden="true" tabindex="-1"></a>p_tb <span class="ot">&lt;-</span> <span class="fl">0.2</span></span>
<span id="cb19-7"><a href="hello-bookdown.html#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of twins</span></span>
<span id="cb19-8"><a href="hello-bookdown.html#cb19-8" aria-hidden="true" tabindex="-1"></a>p_t <span class="ot">&lt;-</span> (p_a <span class="sc">*</span> p_ta) <span class="sc">+</span> ((<span class="dv">1</span> <span class="sc">-</span> p_a) <span class="sc">*</span> p_tb)</span>
<span id="cb19-9"><a href="hello-bookdown.html#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># probability of species A, given twins (using Bayes&#39; Theorem)</span></span>
<span id="cb19-10"><a href="hello-bookdown.html#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># (note this is equivalent to `posterior[1]` above)</span></span>
<span id="cb19-11"><a href="hello-bookdown.html#cb19-11" aria-hidden="true" tabindex="-1"></a>p_at <span class="ot">&lt;-</span> (p_ta <span class="sc">*</span> p_a) <span class="sc">/</span> p_t</span>
<span id="cb19-12"><a href="hello-bookdown.html#cb19-12" aria-hidden="true" tabindex="-1"></a>p_at</span></code></pre></div>
<pre><code>## [1] 0.3333333</code></pre>
<div class="question">
<blockquote>
<p><strong>2H3.</strong> Continuing on from the previous problem, suppose the same panda mother has a second birth and that it is not twins, but a singleton infant. Compute the posterior probability that this panda is species A.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="hello-bookdown.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># likelihood for each species is Pr(twins) * Pr(singleton)</span></span>
<span id="cb21-2"><a href="hello-bookdown.html#cb21-2" aria-hidden="true" tabindex="-1"></a>a_likelihood <span class="ot">&lt;-</span> <span class="fl">0.1</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.1</span>)</span>
<span id="cb21-3"><a href="hello-bookdown.html#cb21-3" aria-hidden="true" tabindex="-1"></a>b_likelihood <span class="ot">&lt;-</span> <span class="fl">0.2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.2</span>)</span>
<span id="cb21-4"><a href="hello-bookdown.html#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># compute posterior probabilities</span></span>
<span id="cb21-5"><a href="hello-bookdown.html#cb21-5" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">c</span>(a_likelihood, b_likelihood)</span>
<span id="cb21-6"><a href="hello-bookdown.html#cb21-6" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb21-7"><a href="hello-bookdown.html#cb21-7" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb21-8"><a href="hello-bookdown.html#cb21-8" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb21-9"><a href="hello-bookdown.html#cb21-9" aria-hidden="true" tabindex="-1"></a>posterior[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.36</code></pre>
<div class="question">
<blockquote>
<p><strong>2H4.</strong> A common boast of Bayesian statisticians is that Bayesian inference makes it easy to use all of the data, even if the data are of different types.<br />
So suppose now that a veterinarian comes along who has a new genetic test that she claims can identify the species of our mother panda. But the test, like all tests, is imperfect. This is the information you have about the test:</p>
<ul>
<li>The probability it correctly identifies a species A panda is 0.8.<br />
</li>
<li>The probability it correctly identifies a species B panda is 0.65.</li>
</ul>
<p>The vet administers the test to your panda and tells you that the test is positive for species A. First ignore your previous information from the births and compute the posterior probability that your panda is species A. Then redo your calculation, now using the birth data as well.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="hello-bookdown.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># use Bayes&#39; Theorem to determine the probability of species A, given a positive</span></span>
<span id="cb23-2"><a href="hello-bookdown.html#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co"># test</span></span>
<span id="cb23-3"><a href="hello-bookdown.html#cb23-3" aria-hidden="true" tabindex="-1"></a>p_ap <span class="ot">&lt;-</span> (<span class="fl">0.8</span> <span class="sc">*</span> <span class="fl">0.5</span>) <span class="sc">/</span> ((<span class="fl">0.5</span> <span class="sc">*</span> <span class="fl">0.8</span>) <span class="sc">+</span> (<span class="fl">0.5</span> <span class="sc">*</span> <span class="fl">0.35</span>))</span>
<span id="cb23-4"><a href="hello-bookdown.html#cb23-4" aria-hidden="true" tabindex="-1"></a>p_ap</span></code></pre></div>
<pre><code>## [1] 0.6956522</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="hello-bookdown.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Now include test data with observed births</span></span>
<span id="cb25-2"><a href="hello-bookdown.html#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># likelihood for each species is Pr(twins) * Pr(singleton)</span></span>
<span id="cb25-3"><a href="hello-bookdown.html#cb25-3" aria-hidden="true" tabindex="-1"></a>a_likelihood <span class="ot">&lt;-</span> <span class="fl">0.1</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.1</span>)</span>
<span id="cb25-4"><a href="hello-bookdown.html#cb25-4" aria-hidden="true" tabindex="-1"></a>b_likelihood <span class="ot">&lt;-</span> <span class="fl">0.2</span> <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> <span class="fl">0.2</span>)</span>
<span id="cb25-5"><a href="hello-bookdown.html#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># compute posterior probabilities, using test result as prior</span></span>
<span id="cb25-6"><a href="hello-bookdown.html#cb25-6" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">c</span>(a_likelihood, b_likelihood)</span>
<span id="cb25-7"><a href="hello-bookdown.html#cb25-7" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">c</span>(p_ap, (<span class="dv">1</span> <span class="sc">-</span> p_ap))</span>
<span id="cb25-8"><a href="hello-bookdown.html#cb25-8" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb25-9"><a href="hello-bookdown.html#cb25-9" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb25-10"><a href="hello-bookdown.html#cb25-10" aria-hidden="true" tabindex="-1"></a>posterior[<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## [1] 0.5625</code></pre>
</div>
<div id="chapter-3" class="section level3" number="2.3.3">
<h3><span class="header-section-number">2.3.3</span> Chapter 3</h3>
<div class="question code-question">
<blockquote>
<p><strong>Easy.</strong> The Easy problems use the sample from the posterior distribution for the globe tossing example. The code will give you a specific set of samples, so that you can check your answers exactly.</p>
</blockquote>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="hello-bookdown.html#cb27-1" aria-hidden="true" tabindex="-1"></a>p_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb27-2"><a href="hello-bookdown.html#cb27-2" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">1000</span>)</span>
<span id="cb27-3"><a href="hello-bookdown.html#cb27-3" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">6</span>, <span class="at">size =</span> <span class="dv">9</span>, <span class="at">prob =</span> p_grid)</span>
<span id="cb27-4"><a href="hello-bookdown.html#cb27-4" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb27-5"><a href="hello-bookdown.html#cb27-5" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb27-6"><a href="hello-bookdown.html#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">100</span>)</span>
<span id="cb27-7"><a href="hello-bookdown.html#cb27-7" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">sample</span>(p_grid, <span class="at">prob =</span> posterior, <span class="at">size =</span> <span class="fl">1e4</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<blockquote>
<p>Use the values in <code>samples</code> to answer the questions that follow.</p>
</blockquote>
</div>
<div class="question">
<blockquote>
<p><strong>3E1.</strong> How much posterior probability lies below <em>p</em> = 0.2?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="hello-bookdown.html#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(samples <span class="sc">&lt;</span> <span class="fl">0.2</span>)</span></code></pre></div>
<pre><code>## [1] 4e-04</code></pre>
<div class="question">
<blockquote>
<p><strong>3E2.</strong> How much posterior probability lies above <em>p</em> = 0.8?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="hello-bookdown.html#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(samples <span class="sc">&gt;</span> <span class="fl">0.8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1116</code></pre>
<div class="question">
<blockquote>
<p><strong>3E3.</strong> How much posterior probability lies between <em>p</em> = 0.2 and <em>p</em> = 0.8?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="hello-bookdown.html#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb32-2"><a href="hello-bookdown.html#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">between</span>(samples, <span class="fl">0.2</span>, <span class="fl">0.8</span>))</span></code></pre></div>
<pre><code>## [1] 0.888</code></pre>
<div class="question">
<blockquote>
<p><strong>3E4.</strong> 20% of the posterior probability lies below which value of <em>p</em>?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="hello-bookdown.html#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(samples, <span class="at">probs =</span> <span class="fl">0.2</span>)</span></code></pre></div>
<pre><code>##       20% 
## 0.5185185</code></pre>
<div class="question">
<blockquote>
<p><strong>3E5.</strong> 20% of the posterior probability lies above which value of <em>p</em>?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="hello-bookdown.html#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(samples, <span class="at">probs =</span> <span class="fl">0.8</span>)</span></code></pre></div>
<pre><code>##       80% 
## 0.7557558</code></pre>
<div class="question">
<blockquote>
<p><strong>3E6.</strong> Which values of <em>p</em> contain the narrowest interval equal to 66% of the posterior probability?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="hello-bookdown.html#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rethinking)</span>
<span id="cb38-2"><a href="hello-bookdown.html#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">HPDI</span>(samples, <span class="at">prob =</span> <span class="fl">0.66</span>)</span></code></pre></div>
<pre><code>##     |0.66     0.66| 
## 0.5085085 0.7737738</code></pre>
<div class="question">
<blockquote>
<p><strong>3E7.</strong> Which values of <em>p</em> contain 66% of the posterior probability, assuming equal posterior probability both below and above the interval?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="hello-bookdown.html#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PI</span>(samples, <span class="at">prob =</span> <span class="fl">0.66</span>)</span></code></pre></div>
<pre><code>##       17%       83% 
## 0.5025025 0.7697698</code></pre>
<div class="question">
<blockquote>
<p><strong>3M1.</strong> Suppose the globe tossing data had turned out to be 8 water in 15 tosses. Constructe the posterior distribution, using grid approximation. Use the same flat prior as before.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="hello-bookdown.html#cb42-1" aria-hidden="true" tabindex="-1"></a>p_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb42-2"><a href="hello-bookdown.html#cb42-2" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">1000</span>)</span>
<span id="cb42-3"><a href="hello-bookdown.html#cb42-3" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">8</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> p_grid)</span>
<span id="cb42-4"><a href="hello-bookdown.html#cb42-4" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb42-5"><a href="hello-bookdown.html#cb42-5" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb42-6"><a href="hello-bookdown.html#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">p =</span> p_grid, <span class="at">posterior =</span> posterior) <span class="sc">%&gt;%</span></span>
<span id="cb42-7"><a href="hello-bookdown.html#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p, <span class="at">y =</span> posterior)) <span class="sc">+</span></span>
<span id="cb42-8"><a href="hello-bookdown.html#cb42-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb42-9"><a href="hello-bookdown.html#cb42-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb42-10"><a href="hello-bookdown.html#cb42-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/e3m1-1.png" width="672" /></p>
<div class="question">
<blockquote>
<p><strong>3M2.</strong> Draw 10,000 samples from the grid approximation from above. Then use the sample to calculate the 90% HPDI for <em>p</em>.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="hello-bookdown.html#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb43-2"><a href="hello-bookdown.html#cb43-2" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">sample</span>(p_grid, <span class="at">prob =</span> posterior, <span class="at">size =</span> <span class="fl">1e4</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb43-3"><a href="hello-bookdown.html#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">HPDI</span>(samples, <span class="at">prob =</span> <span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>##      |0.9      0.9| 
## 0.3343343 0.7217217</code></pre>
<div class="question">
<blockquote>
<p><strong>3M3.</strong> Construct a posterior predictive check for this model and data. The means simulate the distribution of samples, averaging over the posterior uncertainty in <em>p</em>. What is the probability of observing 8 water in 15 tosses?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="hello-bookdown.html#cb45-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fl">1e4</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> samples)</span>
<span id="cb45-2"><a href="hello-bookdown.html#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(w <span class="sc">==</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1499</code></pre>
<div class="question">
<blockquote>
<p><strong>3M4.</strong> Using the posterior distribution constructed from the new (8/15) data, now calculate the probability of observing 6 water in 9 tosses.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="hello-bookdown.html#cb47-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fl">1e4</span>, <span class="at">size =</span> <span class="dv">9</span>, <span class="at">prob =</span> samples)</span>
<span id="cb47-2"><a href="hello-bookdown.html#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(w <span class="sc">==</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.1714</code></pre>
<div class="question">
<blockquote>
<p><strong>3M5.</strong> Start over at <strong>3M1</strong>, but now use a prior that is zero below <em>p</em> = 0.5 and a constant above <em>p</em> = 0.5. This corresponds to prior information that a majority of the Earth’s surface is water. Repeat each problem above and compare the inferences (using both priors) to the true value <em>p</em> = 0.7.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="hello-bookdown.html#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3M5.1</span></span>
<span id="cb49-2"><a href="hello-bookdown.html#cb49-2" aria-hidden="true" tabindex="-1"></a>p_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb49-3"><a href="hello-bookdown.html#cb49-3" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">case_when</span>(p_grid <span class="sc">&lt;</span> <span class="fl">0.5</span> <span class="sc">~</span> 0L,</span>
<span id="cb49-4"><a href="hello-bookdown.html#cb49-4" aria-hidden="true" tabindex="-1"></a>                   <span class="cn">TRUE</span> <span class="sc">~</span> 1L)</span>
<span id="cb49-5"><a href="hello-bookdown.html#cb49-5" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(<span class="dv">8</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> p_grid)</span>
<span id="cb49-6"><a href="hello-bookdown.html#cb49-6" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb49-7"><a href="hello-bookdown.html#cb49-7" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb49-8"><a href="hello-bookdown.html#cb49-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">p =</span> p_grid, <span class="at">posterior =</span> posterior) <span class="sc">%&gt;%</span></span>
<span id="cb49-9"><a href="hello-bookdown.html#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p, <span class="at">y =</span> posterior)) <span class="sc">+</span></span>
<span id="cb49-10"><a href="hello-bookdown.html#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb49-11"><a href="hello-bookdown.html#cb49-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb49-12"><a href="hello-bookdown.html#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/e3m5-1.png" width="672" /></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="hello-bookdown.html#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3M5.2</span></span>
<span id="cb50-2"><a href="hello-bookdown.html#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">101</span>)</span>
<span id="cb50-3"><a href="hello-bookdown.html#cb50-3" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">sample</span>(p_grid, <span class="at">prob =</span> posterior, <span class="at">size =</span> <span class="fl">1e4</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb50-4"><a href="hello-bookdown.html#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">HPDI</span>(samples, <span class="at">prob =</span> <span class="fl">0.9</span>)</span></code></pre></div>
<pre><code>##      |0.9      0.9| 
## 0.5005005 0.7107107</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="hello-bookdown.html#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3M5.3</span></span>
<span id="cb52-2"><a href="hello-bookdown.html#cb52-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fl">1e4</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> samples)</span>
<span id="cb52-3"><a href="hello-bookdown.html#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(w <span class="sc">==</span> <span class="dv">8</span>)</span></code></pre></div>
<pre><code>## [1] 0.1614</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="hello-bookdown.html#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 3M5.4</span></span>
<span id="cb54-2"><a href="hello-bookdown.html#cb54-2" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fl">1e4</span>, <span class="at">size =</span> <span class="dv">9</span>, <span class="at">prob =</span> samples)</span>
<span id="cb54-3"><a href="hello-bookdown.html#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(w <span class="sc">==</span> <span class="dv">6</span>)</span></code></pre></div>
<pre><code>## [1] 0.2362</code></pre>
<p>The HPDI from <strong>3M2</strong> is much narrower with the new prior ([.501, .711] vs. [.334, 0.722]). Additionally, the probabilities of observing 8 in 15 and 6 in 9 have both increased, as value of <em>p</em> &lt; 0.5 are no longer taking up posterior density. Thus the model with the new prior is giving us better information.</p>
<div class="question">
<blockquote>
<p><strong>3M6.</strong> Suppose you want to estimate the Earth’s proportion of water very precisely. Specifically, you want the 99% percentile interval of the posterior distribution of <em>p</em> to be only 0.05 wide. This means the distance between the upper and lower bound of the interval should be 0.05. How many times will you have to toss the globe to do this?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="hello-bookdown.html#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lares)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;lares&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:rethinking&#39;:
## 
##     normalize</code></pre>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="hello-bookdown.html#cb59-1" aria-hidden="true" tabindex="-1"></a>single_sim <span class="ot">&lt;-</span> <span class="cf">function</span>(tosses, <span class="at">prior_type =</span> <span class="fu">c</span>(<span class="st">&quot;uniform&quot;</span>, <span class="st">&quot;step&quot;</span>)) {</span>
<span id="cb59-2"><a href="hello-bookdown.html#cb59-2" aria-hidden="true" tabindex="-1"></a>  prior_type <span class="ot">&lt;-</span> <span class="fu">match.arg</span>(prior_type)</span>
<span id="cb59-3"><a href="hello-bookdown.html#cb59-3" aria-hidden="true" tabindex="-1"></a>  obs <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1</span>, <span class="at">size =</span> tosses, <span class="at">prob =</span> <span class="fl">0.7</span>)</span>
<span id="cb59-4"><a href="hello-bookdown.html#cb59-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-5"><a href="hello-bookdown.html#cb59-5" aria-hidden="true" tabindex="-1"></a>  p_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb59-6"><a href="hello-bookdown.html#cb59-6" aria-hidden="true" tabindex="-1"></a>  prior <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">1000</span>)</span>
<span id="cb59-7"><a href="hello-bookdown.html#cb59-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (prior_type <span class="sc">==</span> <span class="st">&quot;step&quot;</span>) prior[<span class="dv">1</span><span class="sc">:</span><span class="dv">500</span>] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb59-8"><a href="hello-bookdown.html#cb59-8" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-9"><a href="hello-bookdown.html#cb59-9" aria-hidden="true" tabindex="-1"></a>  likelihood <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(obs, <span class="at">size =</span> tosses, <span class="at">prob =</span> p_grid)</span>
<span id="cb59-10"><a href="hello-bookdown.html#cb59-10" aria-hidden="true" tabindex="-1"></a>  posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb59-11"><a href="hello-bookdown.html#cb59-11" aria-hidden="true" tabindex="-1"></a>  posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb59-12"><a href="hello-bookdown.html#cb59-12" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb59-13"><a href="hello-bookdown.html#cb59-13" aria-hidden="true" tabindex="-1"></a>  samples <span class="ot">&lt;-</span> <span class="fu">sample</span>(p_grid, <span class="at">prob =</span> posterior, <span class="at">size =</span> <span class="fl">1e4</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb59-14"><a href="hello-bookdown.html#cb59-14" aria-hidden="true" tabindex="-1"></a>  interval <span class="ot">&lt;-</span> <span class="fu">PI</span>(samples, <span class="at">prob =</span> <span class="fl">0.99</span>)</span>
<span id="cb59-15"><a href="hello-bookdown.html#cb59-15" aria-hidden="true" tabindex="-1"></a>  width <span class="ot">&lt;-</span> interval[<span class="dv">2</span>] <span class="sc">-</span> interval[<span class="dv">1</span>]</span>
<span id="cb59-16"><a href="hello-bookdown.html#cb59-16" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb59-17"><a href="hello-bookdown.html#cb59-17" aria-hidden="true" tabindex="-1"></a>single_cond <span class="ot">&lt;-</span> <span class="cf">function</span>(tosses, prior_type, <span class="at">reps =</span> <span class="dv">100</span>) {</span>
<span id="cb59-18"><a href="hello-bookdown.html#cb59-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tibble</span>(<span class="at">tosses =</span> tosses,</span>
<span id="cb59-19"><a href="hello-bookdown.html#cb59-19" aria-hidden="true" tabindex="-1"></a>         <span class="at">prior_type =</span> prior_type,</span>
<span id="cb59-20"><a href="hello-bookdown.html#cb59-20" aria-hidden="true" tabindex="-1"></a>         <span class="at">width =</span> <span class="fu">map_dbl</span>(<span class="fu">seq_len</span>(reps), <span class="sc">~</span><span class="fu">single_sim</span>(<span class="at">tosses =</span> tosses,</span>
<span id="cb59-21"><a href="hello-bookdown.html#cb59-21" aria-hidden="true" tabindex="-1"></a>                                                    <span class="at">prior_type =</span> prior_type)))</span>
<span id="cb59-22"><a href="hello-bookdown.html#cb59-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb59-23"><a href="hello-bookdown.html#cb59-23" aria-hidden="true" tabindex="-1"></a>simulation <span class="ot">&lt;-</span> <span class="fu">crossing</span>(<span class="at">tosses =</span> <span class="fu">seq</span>(<span class="dv">1000</span>, <span class="dv">5000</span>, <span class="at">by =</span> <span class="dv">100</span>),</span>
<span id="cb59-24"><a href="hello-bookdown.html#cb59-24" aria-hidden="true" tabindex="-1"></a>                       <span class="at">prior_type =</span> <span class="fu">c</span>(<span class="st">&quot;uniform&quot;</span>, <span class="st">&quot;step&quot;</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb59-25"><a href="hello-bookdown.html#cb59-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pmap_dfr</span>(single_cond, <span class="at">reps =</span> <span class="dv">100</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-26"><a href="hello-bookdown.html#cb59-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(tosses, prior_type) <span class="sc">%&gt;%</span></span>
<span id="cb59-27"><a href="hello-bookdown.html#cb59-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">avg_width =</span> <span class="fu">mean</span>(width), <span class="at">.groups =</span> <span class="st">&quot;drop&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb59-28"><a href="hello-bookdown.html#cb59-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prior_type =</span> <span class="fu">case_when</span>(prior_type <span class="sc">==</span> <span class="st">&quot;uniform&quot;</span> <span class="sc">~</span> <span class="st">&quot;Uniform Prior&quot;</span>,</span>
<span id="cb59-29"><a href="hello-bookdown.html#cb59-29" aria-hidden="true" tabindex="-1"></a>                                prior_type <span class="sc">==</span> <span class="st">&quot;step&quot;</span> <span class="sc">~</span> <span class="st">&quot;Step Prior&quot;</span>),</span>
<span id="cb59-30"><a href="hello-bookdown.html#cb59-30" aria-hidden="true" tabindex="-1"></a>         <span class="at">prior_type =</span> <span class="fu">factor</span>(prior_type, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Uniform Prior&quot;</span>,</span>
<span id="cb59-31"><a href="hello-bookdown.html#cb59-31" aria-hidden="true" tabindex="-1"></a>                                                    <span class="st">&quot;Step Prior&quot;</span>)))</span>
<span id="cb59-32"><a href="hello-bookdown.html#cb59-32" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(simulation, <span class="fu">aes</span>(<span class="at">x =</span> tosses, <span class="at">y =</span> avg_width)) <span class="sc">+</span></span>
<span id="cb59-33"><a href="hello-bookdown.html#cb59-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>prior_type, <span class="at">nrow =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb59-34"><a href="hello-bookdown.html#cb59-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb59-35"><a href="hello-bookdown.html#cb59-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb59-36"><a href="hello-bookdown.html#cb59-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_comma</span>() <span class="sc">+</span></span>
<span id="cb59-37"><a href="hello-bookdown.html#cb59-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tosses&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Average Interval Width&quot;</span>) <span class="sc">+</span></span>
<span id="cb59-38"><a href="hello-bookdown.html#cb59-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.spacing.x =</span> <span class="fu">unit</span>(<span class="dv">2</span>, <span class="st">&quot;lines&quot;</span>))</span></code></pre></div>
<p><img src="_main_files/figure-html/e3m6-1.png" width="672" /></p>
<p>This figure shows the average interval width for 100 simulations for the given number of tosses. That is, if the true proportion <em>p</em> is 0.7 and we toss the globe 1,000 times, the average interval width is approximately 0.074. To get an interval width of .05 or smaller, we would need around 2,300 tosses.</p>
<div class="question code-question">
<blockquote>
<p><strong>Hard.</strong> The Hard problems here all use the data below. These data indicate the gender (male = 1, female = 0) of officially reported first and second born children in 100 two-child families. So for example, the first family in the data reported a boy (1) and then a girl (0). The second family reported a girl (0) and then a boy (1). The third family reported two girls. You can load these tow vectors into R’s memory by typing:</p>
</blockquote>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="hello-bookdown.html#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(homeworkch3)</span>
<span id="cb60-2"><a href="hello-bookdown.html#cb60-2" aria-hidden="true" tabindex="-1"></a>birth1</span></code></pre></div>
<pre><code>##   [1] 1 0 0 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0
##  [59] 1 1 0 1 0 0 1 0 0 0 1 0 0 1 1 1 1 0 1 0 1 1 1 1 1 0 0 1 0 1 1 0 1 0 1 1 1 0 1 1 1 1</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="hello-bookdown.html#cb62-1" aria-hidden="true" tabindex="-1"></a>birth2</span></code></pre></div>
<pre><code>##   [1] 0 1 0 1 0 1 1 1 0 0 1 1 1 1 1 0 0 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 1 0 1 0 0 1 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1
##  [59] 1 1 1 0 1 1 0 1 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 0 0</code></pre>
<blockquote>
<p>Use these vectors as data. So for example to compute the total number of boys born across all of these births, you could use:</p>
</blockquote>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="hello-bookdown.html#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(birth1) <span class="sc">+</span> <span class="fu">sum</span>(birth2)</span></code></pre></div>
<pre><code>## [1] 111</code></pre>
</div>
<div class="question">
<blockquote>
<p><strong>3H1.</strong> Using grid approximation, compute the posterior distribution for the probability of a birth being a boy. Assume a uniform prior probability. Which parameter value maximizes the posterior probability?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="hello-bookdown.html#cb66-1" aria-hidden="true" tabindex="-1"></a>p_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)</span>
<span id="cb66-2"><a href="hello-bookdown.html#cb66-2" aria-hidden="true" tabindex="-1"></a>prior <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="dv">1000</span>)</span>
<span id="cb66-3"><a href="hello-bookdown.html#cb66-3" aria-hidden="true" tabindex="-1"></a>boys <span class="ot">&lt;-</span> <span class="fu">sum</span>(birth1) <span class="sc">+</span> <span class="fu">sum</span>(birth2)</span>
<span id="cb66-4"><a href="hello-bookdown.html#cb66-4" aria-hidden="true" tabindex="-1"></a>total <span class="ot">&lt;-</span> <span class="fu">length</span>(birth1) <span class="sc">+</span> <span class="fu">length</span>(birth2)</span>
<span id="cb66-5"><a href="hello-bookdown.html#cb66-5" aria-hidden="true" tabindex="-1"></a>likelihood <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(boys, <span class="at">size =</span> total, <span class="at">prob =</span> p_grid)</span>
<span id="cb66-6"><a href="hello-bookdown.html#cb66-6" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> likelihood <span class="sc">*</span> prior</span>
<span id="cb66-7"><a href="hello-bookdown.html#cb66-7" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior)</span>
<span id="cb66-8"><a href="hello-bookdown.html#cb66-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tibble</span>(<span class="at">p =</span> p_grid, <span class="at">posterior =</span> posterior) <span class="sc">%&gt;%</span></span>
<span id="cb66-9"><a href="hello-bookdown.html#cb66-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p, <span class="at">y =</span> posterior)) <span class="sc">+</span></span>
<span id="cb66-10"><a href="hello-bookdown.html#cb66-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb66-11"><a href="hello-bookdown.html#cb66-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb66-12"><a href="hello-bookdown.html#cb66-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Boys (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/e3h1-1.png" width="672" /></p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="hello-bookdown.html#cb67-1" aria-hidden="true" tabindex="-1"></a>p_grid[<span class="fu">which.max</span>(posterior)]</span></code></pre></div>
<pre><code>## [1] 0.5545546</code></pre>
<div class="question">
<blockquote>
<p><strong>3H2.</strong> Using the <code>sample</code> function, draw 10,000 random parameter values from the posterior distribution you calculated above. Use these sample to estimate the 50%, 89%, and 97% highest posterior density intervals.</p>
</blockquote>
</div>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="hello-bookdown.html#cb69-1" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">sample</span>(p_grid, <span class="at">prob =</span> posterior, <span class="at">size =</span> <span class="fl">1e4</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb69-2"><a href="hello-bookdown.html#cb69-2" aria-hidden="true" tabindex="-1"></a><span class="fu">HPDI</span>(samples, <span class="at">prob =</span> <span class="fu">c</span>(<span class="fl">0.50</span>, <span class="fl">0.89</span>, <span class="fl">0.97</span>))</span></code></pre></div>
<pre><code>##     |0.97     |0.89      |0.5      0.5|     0.89|     0.97| 
## 0.4744745 0.4964965 0.5305305 0.5775776 0.6086086 0.6276276</code></pre>
<div class="question">
<blockquote>
<p><strong>3H3.</strong> Use <code>rbinom</code> to simulate 10,000 replicates of 200 births. You should end up with 10,000 numbers, each one a count of boys out of 200 births. Compare the distribution of predicted numbers of boys to the actual count in the data (111 boys out of 200 births). There are many good ways to visualize the simulations, but the <code>dens</code> command (part of the <code>rethinking</code> package) is prbably the easiest way in this case. Does it look like the model fits the data well? That is, does the distribution of predictions include the actual observation as a central, likely outcome?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="hello-bookdown.html#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidybayes)</span>
<span id="cb71-2"><a href="hello-bookdown.html#cb71-2" aria-hidden="true" tabindex="-1"></a>break_func <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb71-3"><a href="hello-bookdown.html#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">length</span>(<span class="fu">seq</span>(<span class="fu">min</span>(x), <span class="fu">max</span>(x), <span class="at">by =</span> <span class="dv">1</span>)) <span class="sc">+</span> <span class="dv">1</span></span>
<span id="cb71-4"><a href="hello-bookdown.html#cb71-4" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb71-5"><a href="hello-bookdown.html#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">300</span>)</span>
<span id="cb71-6"><a href="hello-bookdown.html#cb71-6" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fl">1e4</span>, <span class="at">size =</span> <span class="dv">200</span>, <span class="at">prob =</span> samples)</span>
<span id="cb71-7"><a href="hello-bookdown.html#cb71-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb71-8"><a href="hello-bookdown.html#cb71-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_histinterval</span>(<span class="fu">aes</span>(<span class="at">x =</span> b), <span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.66</span>, <span class="fl">0.89</span>), <span class="at">breaks =</span> break_func) <span class="sc">+</span></span>
<span id="cb71-9"><a href="hello-bookdown.html#cb71-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> boys), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb71-10"><a href="hello-bookdown.html#cb71-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of Boys&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/e3h3-1.png" width="672" /></p>
<p>Based on this posterior predictive distribution, the model appears to fit well, with the observed value of 111 in the middle of the distribution.</p>
<div class="question">
<blockquote>
<p><strong>3H4.</strong> Now compare 10,000 counts of boys from 100 simulated first borns only the number of boys in the first births, <code>birth1</code>. How does the model look in this light?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb72"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb72-1"><a href="hello-bookdown.html#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">301</span>)</span>
<span id="cb72-2"><a href="hello-bookdown.html#cb72-2" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fl">1e4</span>, <span class="at">size =</span> <span class="dv">100</span>, <span class="at">prob =</span> samples)</span>
<span id="cb72-3"><a href="hello-bookdown.html#cb72-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb72-4"><a href="hello-bookdown.html#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_histinterval</span>(<span class="fu">aes</span>(<span class="at">x =</span> b), <span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.66</span>, <span class="fl">0.89</span>), <span class="at">breaks =</span> break_func) <span class="sc">+</span></span>
<span id="cb72-5"><a href="hello-bookdown.html#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fu">sum</span>(birth1)), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>,</span>
<span id="cb72-6"><a href="hello-bookdown.html#cb72-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb72-7"><a href="hello-bookdown.html#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of Boys&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/e3h4-1.png" width="672" /></p>
<p>Based on first births only, the model appears to fit less well. Specifically, the model appears to be overestimating the number of first births who are boys. However, it does not appear to be a large discrepancy, as the observed value is still within the middle 66% interval.</p>
<div class="question">
<blockquote>
<p><strong>3H5.</strong> The model assumes that sex of first and second births are independent. To check this assumption, focus now on second births that followed female first borns. Compare 10,000 simulated conts of boys to only those second births that followed girls. To do this correctly, you need to count the number of first borns who were girls and simulate that many births, 10,000 times. Compare the counts of boys in your simulations to the actual observed count of boys following girls. How does the model look in this light? Any guesses what is going on in these data?</p>
</blockquote>
</div>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="hello-bookdown.html#cb73-1" aria-hidden="true" tabindex="-1"></a>fb_girls <span class="ot">&lt;-</span> <span class="fu">length</span>(birth1) <span class="sc">-</span> <span class="fu">sum</span>(birth1)</span>
<span id="cb73-2"><a href="hello-bookdown.html#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">302</span>)</span>
<span id="cb73-3"><a href="hello-bookdown.html#cb73-3" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="fl">1e4</span>, <span class="at">size =</span> fb_girls, <span class="at">prob =</span> samples)</span>
<span id="cb73-4"><a href="hello-bookdown.html#cb73-4" aria-hidden="true" tabindex="-1"></a>obs_bfg <span class="ot">&lt;-</span> <span class="fu">sum</span>(birth2[<span class="fu">which</span>(birth1 <span class="sc">==</span> <span class="dv">0</span>)])</span>
<span id="cb73-5"><a href="hello-bookdown.html#cb73-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb73-6"><a href="hello-bookdown.html#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_histinterval</span>(<span class="fu">aes</span>(<span class="at">x =</span> b), <span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.66</span>, <span class="fl">0.89</span>), <span class="at">breaks =</span> break_func) <span class="sc">+</span></span>
<span id="cb73-7"><a href="hello-bookdown.html#cb73-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> obs_bfg), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>,</span>
<span id="cb73-8"><a href="hello-bookdown.html#cb73-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb73-9"><a href="hello-bookdown.html#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Number of Boys&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/3eh5-1.png" width="672" /></p>
<p>The model is severely under estimating the number of second-born boys when the first born child is a girl. Thus, our assumption that births are independent appears to be violated.</p>
</div>
</div>
<div id="homework" class="section level2" number="2.4">
<h2><span class="header-section-number">2.4</span> Homework</h2>
<div class="question">
<blockquote>
<p><strong>1.</strong> Suppose the globe tossing data (Chapter 2) had turned out to be 4 water and 11 land. Construct the posterior distribution, using grid approximation. Use the same flat prior as in the book.</p>
</blockquote>
</div>
<p>First, we create our grid and create our prior, which is a constant for all values of the grid.</p>
<div class="sourceCode" id="cb74"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb74-1"><a href="hello-bookdown.html#cb74-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">p_grid =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>),</span>
<span id="cb74-2"><a href="hello-bookdown.html#cb74-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">prior =</span> <span class="fu">rep</span>(<span class="dv">1</span>, <span class="at">times =</span> <span class="dv">1000</span>))</span>
<span id="cb74-3"><a href="hello-bookdown.html#cb74-3" aria-hidden="true" tabindex="-1"></a>dist</span></code></pre></div>
<pre><code>## # A tibble: 1,000 × 2
##     p_grid prior
##      &lt;dbl&gt; &lt;dbl&gt;
##  1 0           1
##  2 0.00100     1
##  3 0.00200     1
##  4 0.00300     1
##  5 0.00400     1
##  6 0.00501     1
##  7 0.00601     1
##  8 0.00701     1
##  9 0.00801     1
## 10 0.00901     1
## # … with 990 more rows</code></pre>
<p>Next, we calculate the likelihood of 4 water and 11 land for each value of the grid and normalize so that all values sum to 1.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="hello-bookdown.html#cb76-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> dist <span class="sc">%&gt;%</span> </span>
<span id="cb76-2"><a href="hello-bookdown.html#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">likelihood =</span> <span class="fu">dbinom</span>(<span class="dv">4</span>, <span class="at">size =</span> <span class="dv">15</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb76-3"><a href="hello-bookdown.html#cb76-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">posterior =</span> likelihood <span class="sc">*</span> prior,</span>
<span id="cb76-4"><a href="hello-bookdown.html#cb76-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">posterior =</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior))</span>
<span id="cb76-5"><a href="hello-bookdown.html#cb76-5" aria-hidden="true" tabindex="-1"></a>dist</span></code></pre></div>
<pre><code>## # A tibble: 1,000 × 4
##     p_grid prior    likelihood posterior
##      &lt;dbl&gt; &lt;dbl&gt;         &lt;dbl&gt;     &lt;dbl&gt;
##  1 0           1 0              0       
##  2 0.00100     1 0.00000000136  2.17e-11
##  3 0.00200     1 0.0000000214   3.44e-10
##  4 0.00300     1 0.000000107    1.72e- 9
##  5 0.00400     1 0.000000336    5.38e- 9
##  6 0.00501     1 0.000000811    1.30e- 8
##  7 0.00601     1 0.00000166     2.66e- 8
##  8 0.00701     1 0.00000305     4.88e- 8
##  9 0.00801     1 0.00000514     8.23e- 8
## 10 0.00901     1 0.00000814     1.30e- 7
## # … with 990 more rows</code></pre>
<p>Finally, we can sample from and visualize the posterior distribution. The majority of the posterior is below 0.5, with a mean of 0.30. This is not surprising, given that this is what the data indicates (i.e., more land observed than water).</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="hello-bookdown.html#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb78-2"><a href="hello-bookdown.html#cb78-2" aria-hidden="true" tabindex="-1"></a>dist <span class="sc">%&gt;%</span> </span>
<span id="cb78-3"><a href="hello-bookdown.html#cb78-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">10000</span>, <span class="at">weight_by =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb78-4"><a href="hello-bookdown.html#cb78-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p_grid)) <span class="sc">+</span></span>
<span id="cb78-5"><a href="hello-bookdown.html#cb78-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_histinterval</span>(<span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.67</span>, <span class="fl">0.89</span>, <span class="fl">0.97</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.02</span>),</span>
<span id="cb78-6"><a href="hello-bookdown.html#cb78-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">point_interval =</span> mean_hdci) <span class="sc">+</span></span>
<span id="cb78-7"><a href="hello-bookdown.html#cb78-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/w1h1-4-1.png" width="672" /></p>
<div class="question">
<blockquote>
<p><strong>2.</strong> Now suppose the data are 4 water and 2 land. Compute the posterior again, but this time use a prior that is zero below <em>p</em> = 0.5 and a constant above <em>p</em> = 0.5. This corresponds to prior information that a majority of the Earth’s surface is water.</p>
</blockquote>
</div>
<p>We follow the same process, but now we define a prior that is 0 for the <em>p</em> &lt; .5 and 1 for <em>p</em> ≥ .5.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="hello-bookdown.html#cb79-1" aria-hidden="true" tabindex="-1"></a>dist <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">p_grid =</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">0</span>, <span class="at">to =</span> <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>),</span>
<span id="cb79-2"><a href="hello-bookdown.html#cb79-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">prior =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="at">each =</span> <span class="dv">500</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb79-3"><a href="hello-bookdown.html#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">likelihood =</span> <span class="fu">dbinom</span>(<span class="dv">4</span>, <span class="at">size =</span> <span class="dv">6</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb79-4"><a href="hello-bookdown.html#cb79-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">posterior =</span> likelihood <span class="sc">*</span> prior,</span>
<span id="cb79-5"><a href="hello-bookdown.html#cb79-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">posterior =</span> posterior <span class="sc">/</span> <span class="fu">sum</span>(posterior))</span>
<span id="cb79-6"><a href="hello-bookdown.html#cb79-6" aria-hidden="true" tabindex="-1"></a>dist</span></code></pre></div>
<pre><code>## # A tibble: 1,000 × 4
##     p_grid prior likelihood posterior
##      &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;
##  1 0           0   0                0
##  2 0.00100     0   1.50e-11         0
##  3 0.00200     0   2.40e-10         0
##  4 0.00300     0   1.21e- 9         0
##  5 0.00400     0   3.82e- 9         0
##  6 0.00501     0   9.32e- 9         0
##  7 0.00601     0   1.93e- 8         0
##  8 0.00701     0   3.57e- 8         0
##  9 0.00801     0   6.07e- 8         0
## 10 0.00901     0   9.70e- 8         0
## # … with 990 more rows</code></pre>
<p>We now see that the posterior distribution is truncated at .5. The mean is around 0.69, which is expected given that 4 out of 6 trials (two-thirds) were water.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="hello-bookdown.html#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb81-2"><a href="hello-bookdown.html#cb81-2" aria-hidden="true" tabindex="-1"></a>dist <span class="sc">%&gt;%</span> </span>
<span id="cb81-3"><a href="hello-bookdown.html#cb81-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">10000</span>, <span class="at">weight_by =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb81-4"><a href="hello-bookdown.html#cb81-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> p_grid)) <span class="sc">+</span></span>
<span id="cb81-5"><a href="hello-bookdown.html#cb81-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_histinterval</span>(<span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.67</span>, <span class="fl">0.89</span>, <span class="fl">0.97</span>), <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.02</span>),</span>
<span id="cb81-6"><a href="hello-bookdown.html#cb81-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">point_interval =</span> mean_hdci) <span class="sc">+</span></span>
<span id="cb81-7"><a href="hello-bookdown.html#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/w1h2-3-1.png" width="672" /></p>
<div class="question">
<blockquote>
<p><strong>3.</strong> For the posterior distribution from <strong>2</strong>, compute 89% percentile and HPDI intervals. Compare the widths of these intervals. Which is wider? Why? If you had only the information in the interval, what might you misunderstand about the shape of the posterior distribution?</p>
</blockquote>
</div>
<p>First, we take 10,000 samples from the posterior calculated in the previous question. Then we summarize with <code>PI()</code> and <code>HPDI()</code>.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="hello-bookdown.html#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb82-2"><a href="hello-bookdown.html#cb82-2" aria-hidden="true" tabindex="-1"></a>intervals <span class="ot">&lt;-</span> dist <span class="sc">%&gt;%</span> </span>
<span id="cb82-3"><a href="hello-bookdown.html#cb82-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_sample</span>(<span class="at">n =</span> <span class="dv">10000</span>, <span class="at">weight_by =</span> posterior, <span class="at">replace =</span> <span class="cn">TRUE</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb82-4"><a href="hello-bookdown.html#cb82-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">bound =</span> <span class="fu">c</span>(<span class="st">&quot;lower&quot;</span>, <span class="st">&quot;upper&quot;</span>),</span>
<span id="cb82-5"><a href="hello-bookdown.html#cb82-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">pi =</span> <span class="fu">PI</span>(p_grid, <span class="at">prob =</span> <span class="fl">0.89</span>),</span>
<span id="cb82-6"><a href="hello-bookdown.html#cb82-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">hpdi =</span> <span class="fu">HPDI</span>(p_grid, <span class="at">prob =</span> <span class="fl">0.89</span>))</span>
<span id="cb82-7"><a href="hello-bookdown.html#cb82-7" aria-hidden="true" tabindex="-1"></a>intervals</span></code></pre></div>
<pre><code>## # A tibble: 2 × 3
##   bound    pi  hpdi
##   &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 lower 0.525 0.503
## 2 upper 0.882 0.848</code></pre>
<p>The 89% percentile interval is [0.525, 0.882], and the highest posterior density interval is [0.503, 0.848]. The percentile interval is 0.357 wide, and the highest posterior density interval is 0.345 wide. Thus, percentile interval is wider. This is because the HPDI finds the narrowest interval that contains 89% of the data. Therefore, unless the posterior is perfectly symmetrical, the central 89% will, by definition, be wider than the HDPI.</p>
<p>For both intervals, the only boundary information is conveyed. No information about the actual shape of the posterior is conveyed. Without visualizing the posterior, the interval boundaries might tempt us to (incorrectly) assume that all values in the interval are equally likely or that values in the middle of the range are the most plausible. However, we know from the previous problem that the posterior is asymmetrical, with values closer to the low end of the interval more plausible than values at the high end of the interval.</p>
<div class="question">
<blockquote>
<p><strong>4.</strong> OPTIONAL CHALLENGE. Suppose there is bias in sampling so that Land is more likely than Water to be recorded. Specifically, assume that 1-in-5 (20%) of Water samples are accidentally recorded instead as “Land.” First, write a generative simulation of this sampling process. Assuming the true proportion of Water is 0.70, what proportion does your simulation tend to produce instead? Second, using a simulated sample of 20 tosses, compute the unbiased posterior distribution of the true proportion of water.</p>
</blockquote>
</div>
<p>We’ll start by writing a function to generate the biased data. First, we generate the specified number of <code>tosses</code> with the <code>true_prop</code>. Normally, we would use <code>rbinom(n = 1, size = tosses)</code>, but this will only provide the total number of successes (tosses with a “water” result). We want the results from each individual toss. So, as an example, rather than 1 trial of 100 tosses, we do 100 trials of 1 toss.</p>
<p>Next, we generate random uniform numbers between 0 and 1. These indicate which trials are biased. For every element of <code>bias_sim</code> that is less than <code>bias</code>, the corresponding element of <code>true_trials</code> is changed to 0 in a new vector called <code>bias_trials</code>. If the original results was 0 (“land”), then the bias has no effect (i.e., 0 is changed to 0). If the original result was 1 (“water”), then there is a <code>bias</code> chance that the result will be changed to 0.</p>
<p>Finally, we sum the total number of 1s (“water”) after implementing the bias and return the results.</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="hello-bookdown.html#cb84-1" aria-hidden="true" tabindex="-1"></a>biased_globe <span class="ot">&lt;-</span> <span class="cf">function</span>(<span class="at">tosses =</span> <span class="dv">100</span>, <span class="at">true_prop =</span> <span class="fl">0.7</span>, <span class="at">bias =</span> <span class="fl">0.2</span>) {</span>
<span id="cb84-2"><a href="hello-bookdown.html#cb84-2" aria-hidden="true" tabindex="-1"></a>  true_trials <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="at">n =</span> tosses, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">prob =</span> true_prop)</span>
<span id="cb84-3"><a href="hello-bookdown.html#cb84-3" aria-hidden="true" tabindex="-1"></a>  bias_sim <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="at">n =</span> tosses, <span class="at">min =</span> <span class="dv">0</span>, <span class="at">max =</span> <span class="dv">1</span>)</span>
<span id="cb84-4"><a href="hello-bookdown.html#cb84-4" aria-hidden="true" tabindex="-1"></a>  bias_trials <span class="ot">&lt;-</span> true_trials</span>
<span id="cb84-5"><a href="hello-bookdown.html#cb84-5" aria-hidden="true" tabindex="-1"></a>  bias_trials[<span class="fu">which</span>(bias_sim <span class="sc">&lt;</span> bias)] <span class="ot">&lt;-</span> 0L</span>
<span id="cb84-6"><a href="hello-bookdown.html#cb84-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(bias_trials)</span>
<span id="cb84-7"><a href="hello-bookdown.html#cb84-7" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>What does this bias mean for our estimated proportion of water? To explore, we’ll run a short simulation. We’ll use our <code>biased_globe()</code> function to do 1,000 simulations of 100 tosses. For each of the simulations, we can see the proportion of tosses that were water, with the bias included.</p>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="hello-bookdown.html#cb85-1" aria-hidden="true" tabindex="-1"></a>bias_prop <span class="ot">&lt;-</span> <span class="fu">map_int</span>(<span class="fu">seq_len</span>(<span class="dv">1000</span>),</span>
<span id="cb85-2"><a href="hello-bookdown.html#cb85-2" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">~</span><span class="fu">biased_globe</span>(<span class="at">tosses =</span> <span class="dv">100</span>, <span class="at">true_prop =</span> <span class="fl">0.7</span>, <span class="at">bias =</span> <span class="fl">0.2</span>))</span>
<span id="cb85-3"><a href="hello-bookdown.html#cb85-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb85-4"><a href="hello-bookdown.html#cb85-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_histinterval</span>(<span class="fu">aes</span>(<span class="at">x =</span> bias_prop <span class="sc">/</span> <span class="dv">100</span>), <span class="at">.width =</span> <span class="fu">c</span>(<span class="fl">0.67</span>, <span class="fl">0.89</span>, <span class="fl">0.97</span>),</span>
<span id="cb85-5"><a href="hello-bookdown.html#cb85-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.01</span>)) <span class="sc">+</span></span>
<span id="cb85-6"><a href="hello-bookdown.html#cb85-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="fu">aes</span>(<span class="at">xintercept =</span> <span class="fl">0.7</span>), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb85-7"><a href="hello-bookdown.html#cb85-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">expand_limits</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb85-8"><a href="hello-bookdown.html#cb85-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Simulations&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/w1h4-2-1.png" width="672" /></p>
<p>In the previous figure, the true proportion, 0.7, is indicated by the dashed red line. However, we can see that the biased tosses are greatly reducing the number of “waters” that we actually observe. On average, we observe 56 waters, for an estimated proportion of 0.56.</p>
<p>Our final step is to compute an unbiased posterior distribution of the true proportion of water, using 20 tosses from the biased data generation process. We’ll start by generating our 20 tosses.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="hello-bookdown.html#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb86-2"><a href="hello-bookdown.html#cb86-2" aria-hidden="true" tabindex="-1"></a>biased_dat <span class="ot">&lt;-</span> <span class="fu">biased_globe</span>(<span class="at">tosses =</span> <span class="dv">20</span>)</span>
<span id="cb86-3"><a href="hello-bookdown.html#cb86-3" aria-hidden="true" tabindex="-1"></a>biased_dat</span></code></pre></div>
<pre><code>## [1] 11</code></pre>
<p>In our data, we observed 11 waters. Our final step is to estimate the unbiased posterior. We can accomplish this by using the biased sampling rate of 0.8. That is, each true water observation has an 80% chance of actually being recorded as a water observation. This is shown in the <code>crtd_likelihood</code> line below. In the <code>dbinom()</code> function, rather than setting <code>prob = p_grid</code>, we set <code>prob = p_grid * 0.8</code>, to reflect the bias in sampling. We then see that the biased posterior peaks around 0.55, whereas correcting for the bias results in a posterior that peaks right around 0.70.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="hello-bookdown.html#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geomtextpath)</span>
<span id="cb88-2"><a href="hello-bookdown.html#cb88-2" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">p_grid =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">length.out =</span> <span class="dv">1000</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb88-3"><a href="hello-bookdown.html#cb88-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prior =</span> <span class="fu">dbeta</span>(p_grid, <span class="at">shape1 =</span> <span class="dv">1</span>, <span class="at">shape2 =</span> <span class="dv">1</span>),</span>
<span id="cb88-4"><a href="hello-bookdown.html#cb88-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_likelihood =</span> <span class="fu">dbinom</span>(biased_dat, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> p_grid),</span>
<span id="cb88-5"><a href="hello-bookdown.html#cb88-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">crtd_likelihood =</span> <span class="fu">dbinom</span>(biased_dat, <span class="at">size =</span> <span class="dv">20</span>, <span class="at">prob =</span> p_grid <span class="sc">*</span> <span class="fl">0.8</span>),</span>
<span id="cb88-6"><a href="hello-bookdown.html#cb88-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_posterior =</span> bias_likelihood <span class="sc">*</span> prior,</span>
<span id="cb88-7"><a href="hello-bookdown.html#cb88-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">crtd_posterior =</span> crtd_likelihood <span class="sc">*</span> prior,</span>
<span id="cb88-8"><a href="hello-bookdown.html#cb88-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">bias_posterior =</span> bias_posterior <span class="sc">/</span> <span class="fu">sum</span>(bias_posterior),</span>
<span id="cb88-9"><a href="hello-bookdown.html#cb88-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">crtd_posterior =</span> crtd_posterior <span class="sc">/</span> <span class="fu">sum</span>(crtd_posterior))</span>
<span id="cb88-10"><a href="hello-bookdown.html#cb88-10" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(posterior, <span class="fu">aes</span>(<span class="at">x =</span> p_grid)) <span class="sc">+</span></span>
<span id="cb88-11"><a href="hello-bookdown.html#cb88-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_textline</span>(<span class="fu">aes</span>(<span class="at">y =</span> bias_posterior), <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>, <span class="at">color =</span> <span class="st">&quot;grey70&quot;</span>,</span>
<span id="cb88-12"><a href="hello-bookdown.html#cb88-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> <span class="dv">6</span>, <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">label =</span> <span class="st">&quot;Biased&quot;</span>, <span class="at">hjust =</span> <span class="fl">0.45</span>,</span>
<span id="cb88-13"><a href="hello-bookdown.html#cb88-13" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="st">&quot;Source Sans Pro&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-14"><a href="hello-bookdown.html#cb88-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_textline</span>(<span class="fu">aes</span>(<span class="at">y =</span> crtd_posterior), <span class="at">linetype =</span> <span class="st">&quot;solid&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#009FB7&quot;</span>,</span>
<span id="cb88-15"><a href="hello-bookdown.html#cb88-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">size =</span> <span class="dv">6</span>, <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">label =</span> <span class="st">&quot;Corrected&quot;</span>, <span class="at">hjust =</span> <span class="fl">0.4</span>,</span>
<span id="cb88-16"><a href="hello-bookdown.html#cb88-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">family =</span> <span class="st">&quot;Source Sans Pro&quot;</span>) <span class="sc">+</span></span>
<span id="cb88-17"><a href="hello-bookdown.html#cb88-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb88-18"><a href="hello-bookdown.html#cb88-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Proportion Water (p)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Posterior Density&quot;</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/w1h4-4-1.png" width="672" /></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="cross.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/agberg/statistical_rethinking_workbook/edit/main/01-intro.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
