---
title: "Chapter 2"
output: html_notebook
---

```{r}
library(ggplot2)
library(rethinking)
```



```{r 2.3}

# define grid

p_grid <- seq(from = 0, to = 1, length.out = 20)

# define prior

# prior <- rep(1, 20)
# prior <- ifelse(p_grid < 0.5, 0, 1)
prior <- exp(-5*abs(p_grid-.5))

prior <- prior/sum(prior)

# compute likelihood at each value in grid

likelihood <- dbinom(6, size = 9, prob = p_grid)
likelihood <- likelihood/sum(likelihood)

# compute product of likelihood and prior
unstd.posterior <- likelihood * prior

# standardize the posterior, so it sums to 1
posterior <- unstd.posterior / sum(unstd.posterior)

plot(p_grid, posterior, type = "b",
     xlab = "probability of water", ylab = "posterior probability")
mtext("20 points")


to_plot <- tibble::tibble(p_grid, prior, posterior, likelihood)

ggplot(data = to_plot, mapping = aes(x=p_grid, y=posterior)) +
  geom_point() +
  geom_line() +
  geom_line(mapping = aes(y=prior, alpha = .5, color = "prior")) +
  geom_line(mapping = aes(y=likelihood, alpha = .5, color = "likelihood"))


```

```{r}

globe.qa <- quap(
  
  
  
)


```

